### PR TITLE
Changed discord message to embedded to fix formatting error

### PR DESCRIPTION
**Pull request by SkOODaT**
Future ToDo: status colours

### CODE REVIEW

**Comment by georgeherby** [comment]
Hey, what is this fixing, specifically?

**Comment by SkOODaT** [comment]
were chatting about it on the discord .... last data isnt making it through, last discord update messed up code blocks in some way, i couldn't figure it out so i just added it to an embedded message and it works fine, krzTrack asked if i could submit it as a PR

**Comment by georgeherby** [comment]
Okay understood. I will review fully when I get a chance in the coming days

**Comment by georgeherby** [comment]
I have resolved conflicts on develop and will merge for testing

**Comment by georgeherby** [comment]
Also @SkOODaT i added the status code stuff you Todo'd

**Pull request merged**
